android: minimp3: Avoid redefinition of datatypes
Under Linux OS there's no need to redefine int64_t as a data type
still including sys/types.h to take care of any missing data types.

The following compilation errors are thrown if int64_t is defined:

Error:(50, 36) error: typedef redefinition with different types
 ('unsigned long long' vs '__uint64_t' (aka 'unsigned long'))
Error:(51, 37) error: typedef redefinition with different types
 ('long long' vs '__int64_t' (aka 'long'))

Issue: https://github.com/XProger/OpenLara/issues/67

Signed-off-by: Carlos Santa <santa.cm@gmail.com>